<!DOCTYPE html>
<html lang="pl">
   <head>
      <title>Komis Sam</title>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="/views/pojazdy/css/style.css">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
   </head>
   <body style="background-color: #fff">
      <?php $detale = $data['detale']; ?>
      <div id="demo" class="carousel slide" data-ride="carousel">
         <!-- Indicators -->
         <ul class="carousel-indicators">
            <li data-target="#demo" data-slide-to="0" class="active"></li>
            <li data-target="#demo" data-slide-to="1"></li>
            <li data-target="#demo" data-slide-to="2"></li>
         </ul>
         <!-- The slideshow -->
         <div class="carousel-inner">
            <div class="carousel-item active">
               <img src="/views/pojazdy/img/karuzela_1.jpg" alt="1" width="1100" height="100">
            </div>
            <div class="carousel-item">
               <img src="/views/pojazdy/img/karuzela_2.jpg" alt="2" width="1100" height="500">
            </div>
            <div class="carousel-item">
               <img src="/views/pojazdy/img/karuzela_3.jpg" alt="3" width="1100" height="500">
            </div>
         </div>
         <!-- Left and right controls -->
         <a class="carousel-control-prev" href="#demo" data-slide="prev">
         <span class="carousel-control-prev-icon"></span>
         </a>
         <a class="carousel-control-next" href="#demo" data-slide="next">
         <span class="carousel-control-next-icon"></span>
         </a>
      </div>
      <div class="sticky-top">
         <nav class="navbar navbar-expand-sm bg-dark navbar-dark" style="background-color: #1b1b1b!important">
            <a class="navbar-brand" href="../../pojazdy/" style="padding: 0px; padding-left: 20px">
            <img src="/views/pojazdy/img/logo2.png" alt="logo">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
               <ul class="navbar-nav">
                  <li class="nav-item menu-button-active">
                     <a class="nav-link menu-link" href="../../pojazdy/">Pojazdy</a>
                  </li>
                  <li class="nav-item menu-button">
                     <a class="nav-link menu-link" href="../../raporty/">Raporty</a>
                  </li>
                  <li class="nav-item menu-button">
                     <a class="nav-link menu-link" href="#!" data-toggle="modal" data-target="#myModal"
                        data-backdrop="static">Dodaj Pojazd</a>
                  </li>
                  <li class="nav-item" style="margin-left: 20px">
                     <form id="search-bar-form" class="form-inline" action="#">
                        <div class="input-group">
                           <div class="input-group-prepend">
                              <button data-toggle="collapse" data-target="#filers-container" id="search-filter-btn"
                                 type="button" class="btn btn-default" data-toggle="dropdown">
                              <i class="fa fa-arrow-circle-down" aria-hidden="true"></i>
                              </button>
                           </div>
                           <input id="search-bar" class="form-control py-2 border-right-0 border" type="search"
                              placeholder="Szukaj..." id="example-search-input">
                           <span class="input-group-append">
                           <button class="btn btn-outline-secondary border-left-0 border"
                              style="background-color: #ff9900; outline: 0!important; border: none!important;" type="button">
                           <i class="fa fa-search fa-fw"></i>
                           </button>
                           </span>
                        </div>
                     </form>
                  </li>
               </ul>
            </div>
         </nav>
         <div id="filers-container" class="container-fluid collapse small-text"
            style="background-color: #1b1b1b; color: #fff">
            <form>
               <div class="row">
                  <div class="col-sm-1"></div>
                  <div class="col-sm-2">
                     <div class="card filters-card">
                        <div class="card-body filters-card-body">
                           <div class="form-group">
                              <label for="sel1">Marka:</label>
                              <select class="form-control form-control-sm input-dark" id="sel1">
                                 <option>1</option>
                                 <option>22</option>
                                 <option>3333</option>
                                 <option>44444</option>
                              </select>
                           </div>
                           <div class="form-group">
                              <label for="sel3">Model:</label>
                              <select class="form-control form-control-sm input-dark" id="sel3">
                                 <option>1</option>
                                 <option>2</option>
                                 <option>3</option>
                                 <option>4</option>
                              </select>
                           </div>
                           <div class="form-group">
                              <label for="sel2">Rocznik:</label>
                              <select class="form-control form-control-sm input-dark" id="sel2">
                                 <option>1</option>
                                 <option>2</option>
                                 <option>3</option>
                                 <option>4</option>
                                 <option>5</option>
                              </select>
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class="col-sm-4">
                     <div class="card filters-card">
                        <div class="card-body filters-card-body">
                           <span style="display: inline-block; margin-bottom: .5rem;">Cena:</span>
                           <div style="display: flex; text-align: center; vertical-align: middle; align-items: center">
                              <div class="form-group"
                                 style="display: flex; text-align: center; vertical-align: middle;align-items: center">
                                 <label for="sel5"
                                    style="align-items: center; margin-bottom: 0; padding-right: 10px;">Od:</label>
                                 <input class="form-control form-control-sm input-dark" id="sel5" type="text"
                                    placeholder="0">
                              </div>
                              <div class="form-group"
                                 style="display: flex; text-align: center; vertical-align: middle;align-items: center">
                                 <label for="sel6"
                                    style="align-items: center; margin-bottom: 0;padding-left: 10px; padding-right: 10px;">Do:</label>
                                 <input class="form-control form-control-sm input-dark" id="sel6" type="text"
                                    placeholder="100 000">
                                 <span style="padding-left: 5px;">zł</span>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class="col-sm-2">
                     <div class="card filters-card">
                        <div class="card-body filters-card-body">
                           <div class="form-group">
                              <label for="sel9">Maksymalny przebieg:</label>
                              <div style="display: flex; text-align: center; vertical-align: middle; align-items: center">
                                 <input type="text" class="form-control form-control-sm input-dark" id="sel9"
                                    style="display: flex; width: 80%">
                                 <span style="padding-left: 5px; display: flex;">km</span>
                              </div>
                           </div>
                           <div class="form-group">
                              <label for="sel10">Typ:</label>
                              <select class="form-control form-control-sm input-dark" id="sel10" style="width: 80%">
                                 <option>1</option>
                                 <option>2</option>
                                 <option>3</option>
                                 <option>4</option>
                              </select>
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class="col-sm-2"></div>
               </div>
            </form>
         </div>
      </div>
      <!-- Modal nowy pojazd-->
      <div class="modal fade" id="myModal" role="dialog">
         <div class="modal-dialog modal-dialog-centered">
            <!-- Modal content-->
            <div class="modal-content">
               <form action="../pojazdy/dodaj" method="post">
                  <div class="modal-header text-center" style="background-color: #ff9900">
                     <h4 class="modal-title w-100 font-weight-bold">Nowy pojazd</h4>
                     <button aria-label="Close" class="close" data-dismiss="modal" type="button"><span
                        aria-hidden="true">&times;</span></button>
                  </div>
                  <div class="modal-body">
                     <div class="container-fluid">
                        <div class="form-group form-row">
                           <label class="col-sm-3" data-error="wrong" data-success="right" for="marka">Marka</label>
                           <div class="col-sm-9">
                              <select class="form-control form-control-sm" id="nowy-marka-dropdown"
                                 title="Wybierz markę!" required>
                              </select>
                           </div>
                        </div>
                        <div class="form-group form-row">
                           <label class="col-sm-3" data-error="wrong" data-success="right" for="model">Model</label>
                           <div class="col">
                              <select name="model" class="form-control form-control-sm" id="nowy-model-dropdown"
                                 disabled required>
                              </select>
                           </div>
                        </div>
                        <div class="form-group form-row">
                           <label class="col-sm-3" data-error="wrong" data-success="right"
                              for="przebieg">Przebieg</label>
                           <div class="col-sm-9">
                              <input name="mileage" class="form-control form-control-sm validate" id="przebieg-nowy"
                                 type="text" title="Podaj liczbę całkowitą" placeholder="0" required
                                 pattern="[0-9]+">
                           </div>
                        </div>
                        <div class="form-group form-row">
                           <label class="col-sm-3" data-error="wrong" data-success="right" for="cena">Cena</label>
                           <div class="col-sm-9">
                              <input name="price" class="form-control form-control-sm validate" id="cena-nowy"
                                 type="text" placeholder="0" required title="Podaj liczbę całkowitą!"
                                 pattern="[0-9]+">
                           </div>
                        </div>
                        <div class="form-group form-row">
                           <label class="col-sm-3" data-error="wrong" data-success="right" for="vin">VIN</label>
                           <div class="col-sm-9">
                              <input name="vin" class="form-control form-control-sm validate" id="vin-nowy"
                                 type="text" title="Błędny numer VIN!" required pattern="[0-9A-Z]{17}">
                           </div>
                        </div>
                        <div class="form-group form-row">
                           <label class="col-sm-3" data-error="wrong" data-success="right" for="registrationNumber">Numer
                           rejestracyjny</label>
                           <div class="col-sm-9">
                              <input name="registrationNumber" class="form-control form-control-sm validate"
                                 id="rejestracja-nowy" type="text" required pattern="[0-9A-Z]+">
                           </div>
                        </div>
                        <div class="form-group form-row">
                           <label class="col-sm-3" data-error="wrong" data-success="right" for="color">Kolor</label>
                           <div class="col-sm-9">
                              <select name="color" class="form-control form-control-sm" id="nowy-kolor-dropdown">
                                 <option value="Czarny">Czarny</option>
                                 <option value="Czerwony">Czerwony</option>
                                 <option value="Zielony">Zielony</option>
                                 <option value="Niebieski">Niebieski</option>
                                 <option value="Biały">Biały</option>
                                 <option value="Inny">Inny</option>
                              </select>
                           </div>
                        </div>
                        <div class="form-group form-row">
                           <label class="col-sm-3" data-error="wrong" data-success="right" for="cena">Rok
                           produkcji</label>
                           <div class="col-sm-9">
                              <input name="productionYear" class="form-control form-control-sm validate"
                                 id="rocznik-nowy" type="text"
                                 title="Podaj 4 cyfry" required pattern="[0-9]{4}">
                           </div>
                        </div>
                        <div class="form-group form-row">
                           <label class="col-sm-3" data-error="wrong" data-success="right" for="doorsNumber">Liczba
                           drzwi</label>
                           <div class="col-sm-9">
                              <select name="doorsNumber" class="form-control form-control-sm"
                                 id="nowy-drzwi-dropdown">
                                 <option value="2">2</option>
                                 <option value="3">3</option>
                                 <option value="4">4</option>
                                 <option value="5">5</option>
                              </select>
                           </div>
                        </div>
                        <div class="form-group form-row">
                           <label class="col-sm-3" data-error="wrong" data-success="right" for="seatsNumber">Liczba
                           miejsc</label>
                           <div class="col-sm-9">
                              <select name="seatsNumber" class="form-control form-control-sm"
                                 id="nowy-miejsca-dropdown">
                                 <option value="1">1</option>
                                 <option value="2">2</option>
                                 <option value="3">3</option>
                                 <option value="4">4</option>
                                 <option value="5">5</option>
                                 <option value="6">6</option>
                              </select>
                           </div>
                        </div>
                        <div class="form-group form-row">
                           <label class="col-sm-3" data-error="wrong" data-success="right" for="additionalDescription">Opis</label>
                           <div class="col">
                              <textarea name="additionalDescription" class="form-control form-control-sm validate"
                                 id="opis-nowy" rows="3"></textarea>
                           </div>
                        </div>
                        <div class="form-group form-row">
                           <div class="col clearfix align-items-center row-eq-height text-center">
                              <h5>Właściciel pojazdu</h5>
                           </div>
                        </div>
                        <div class="form-group form-row">
                           <label class="col-sm-3" data-error="wrong" data-success="right"
                              for="ownerFirstName">Imię</label>
                           <div class="col-sm-9">
                              <input name="ownerFirstName" class="form-control form-control-sm validate"
                                 id="wlasciciel-imie-nowy"
                                 type="text" title="Podaj poprawne imie" required
                                 pattern="[A-Z]{1}[a-z]+">
                           </div>
                        </div>
                        <div class="form-group form-row">
                           <label class="col-sm-3" data-error="wrong" data-success="right"
                              for="ownerLastName">Nazwisko</label>
                           <div class="col-sm-9">
                              <input name="ownerLastName" class="form-control form-control-sm validate"
                                 id="wlasciciel-nazwisko-nowy"
                                 type="text" title="Podaj poprawne nazwisko" required pattern="[A-Z]{1}[a-z]+">
                           </div>
                        </div>
                        <div class="form-group form-row">
                           <label class="col-sm-3" data-error="wrong" data-success="right"
                              for="ownerEmail">Email</label>
                           <div class="col-sm-9">
                              <input name="ownerEmail" class="form-control form-control-sm validate"
                                 id="wlasciciel-email-nowy"
                                 type="text" title="Podaj poprawny adres email" required
                                 pattern="[A-Za-z0-9.]+[@][A-Za-z0-9]+[.][A-Za-z0-9]+">
                           </div>
                        </div>
                        <div class="form-group form-row">
                           <div class="col clearfix align-items-center row-eq-height text-center">
                              <button type="button" class="btn btn-link yellow-link" data-toggle="collapse"
                                 data-target="#wyposazenie-collapse"><i class="fa fa-tachometer"
                                 aria-hidden="true"></i> Dodatkowe
                              wyposażenie
                              </button>
                              <div id="wyposazenie-collapse" class="collapse row text-center">
                                 <div class="col-sm-12 align-items-center">
                                    <?php foreach ($data['listAllEquipment'] as $equipment) { ?>
                                    <div class="checkbox">
                                       <label><input type="checkbox" name="additionalEquipment[]"
                                          value="<?= $equipment['name'] ?>"> <?= $equipment['name'] ?>
                                       </label>
                                    </div>
                                    <?php } ?>
                                 </div>
                              </div>
                           </div>
                        </div>
                        <hr>
                        <div class="form-group form-row justify-content-center align-items-center">
                           <input type="submit" class="btn btn-green-submit align-items-center"
                              id="submit-nowy"
                              value="Zapisz">
                        </div>
                     </div>
                  </div>
               </form>
            </div>
         </div>
      </div>
      <!-- !Modal nowy pojazd -->
      <!-- Modal edytuj pojazd-->
      <div id="modalEdytujPojazd" class="modal fade" role="dialog">
         <div class="modal-dialog modal-dialog-centered">
            <!-- Modal content-->
            <div class="modal-content">
               <div class="modal-header text-center" style="background-color: #2EC4B6">
                  <h4 class="modal-title w-100 font-weight-bold">Edytuj pojazd</h4>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                  </button>
               </div>
               <div class="modal-body">
                  <div class="container-fluid">
                     <form method="POST" action="/pojazdy/edytuj/<?= $detale['id'] ?>">
                        <div class="form-group form-row">
                           <label class="col-sm-3" data-error="wrong" data-success="right" for="marka">Marka</label>
                           <div class="col-sm-9">
                              <input type="hidden" id="aktualna-marka" name="akt-mar" value="<?= $detale['brand'] ?>">
                              <select class="form-control form-control-sm" id="edytuj-marka-dropdown" name="brand" title="Wybierz markę!" required>
                              </select>
                           </div>
                        </div>
                        <div class="form-group form-row">
                           <label class="col-sm-3" data-error="wrong" data-success="right" for="model">Model</label>
                           <div class="col">
                              <input type="hidden" id="aktualny-model" name="akt-mod" value="<?= $detale['model'] ?>">
                              <select class="form-control form-control-sm" id="edytuj-model-dropdown" name="model" required>
                              </select>
                           </div>
                        </div>
                        <div class="form-group form-row">
                           <label class="col-sm-3" data-error="wrong" data-success="right"
                              for="przebieg">Przebieg</label>
                           <div class="col-sm-9">
                              <input name="mileage" class="form-control form-control-sm validate" id="przebieg-nowy"
                                 type="text" title="Podaj liczbę całkowitą" placeholder="0" required
                                 pattern="[0-9]+" value="<?= $detale['mileage'] ?>">
                           </div>
                        </div>
                        <div class="form-group form-row">
                           <label class="col-sm-3" data-error="wrong" data-success="right" for="cena">Cena</label>
                           <div class="col-sm-9">
                              <input name="price" class="form-control form-control-sm validate" id="cena-nowy"
                                 type="text" placeholder="0" required title="Podaj liczbę całkowitą!"
                                 pattern="[0-9]+" value="<?= $detale['price'] ?>">
                           </div>
                        </div>
                        <div class="form-group form-row">
                           <label class="col-sm-3" data-error="wrong" data-success="right" for="vin">VIN</label>
                           <div class="col-sm-9">
                              <input name="vin" class="form-control form-control-sm validate" id="vin-nowy"
                                 type="text" title="Błędny numer VIN!" required pattern="[0-9A-Z]{17}"
                                 value="<?= $detale['vin'] ?>">
                           </div>
                        </div>
                        <div class="form-group form-row">
                           <label class="col-sm-3" data-error="wrong" data-success="right" for="registrationNumber">Numer
                           rejestracyjny</label>
                           <div class="col-sm-9">
                              <input name="registrationNumber" class="form-control form-control-sm validate"
                                 id="rejestracja-nowy" value="<?= $detale['registrationNumber'] ?>" type="text"
                                 required pattern="[0-9A-Z]+">
                           </div>
                        </div>
                        <div class="form-group form-row">
                           <label class="col-sm-3" data-error="wrong" data-success="right" for="color">Kolor</label>
                           <div class="col-sm-9">
                              <select name="color" class="form-control form-control-sm" id="nowy-kolor-dropdown">
                              <?php
                                 $defColor = $detale['color'];
                                 $colors = array("Czarny", "Czerowny", "Zielony", "Niebieski", "Biały", "Inny");
                                 $nr = 0;
                                 while($nr < count($colors)){
                                     if($colors[$nr] == $defColor){
                                         echo "<option selected=\"selected\" value=\"$colors[$nr]\">". $colors[$nr] ."</option>";
                                     }
                                     else{
                                         echo "<option value=\"$colors[$nr]\">". $colors[$nr] ."</option>";
                                     }
                                     $nr++;
                                 }
                                 ?>
                              </select>
                           </div>
                        </div>
                        <div class="form-group form-row">
                           <label class="col-sm-3" data-error="wrong" data-success="right" for="cena">Rok
                           produkcji</label>
                           <div class="col-sm-9">
                              <input name="productionYear" class="form-control form-control-sm validate"
                                 id="rocznik-nowy" type="text" value="<?= $detale['productionYear'] ?>"
                                 title="Podaj 4 cyfry" required pattern="[0-9]{4}">
                           </div>
                        </div>
                        <div class="form-group form-row">
                           <label class="col-sm-3" data-error="wrong" data-success="right" for="doorsNumber">Liczba
                           drzwi</label>
                           <div class="col-sm-9">
                              <select name="doorsNumber" class="form-control form-control-sm"
                                 id="nowy-drzwi-dropdown">
                              <?php
                                 $defDoors = $detale['doorsNumber'];
                                 $doors = array("2", "3", "4", "5", "6");
                                 $nr = 0;
                                 while($nr < count($doors)){
                                     if($doors[$nr] == $defDoors){
                                         echo "<option selected=\"selected\" value=\"$doors[$nr]\">". $doors[$nr] ."</option>";
                                     }
                                     else{
                                         echo "<option value=\"$doors[$nr]\">". $doors[$nr] ."</option>";
                                     }
                                     $nr++;
                                 }
                                 ?>
                              </select>
                           </div>
                        </div>
                        <div class="form-group form-row">
                           <label class="col-sm-3" data-error="wrong" data-success="right" for="seatsNumber">Liczba
                           miejsc</label>
                           <div class="col-sm-9">
                              <select name="seatsNumber" class="form-control form-control-sm"
                                 id="nowy-miejsca-dropdown">
                              <?php
                                 $defSeats = $detale['seatsNumber'];
                                 $seats = array("1","2", "3", "4", "5", "6");
                                 $nr = 0;
                                 while($nr < count($seats)){
                                     if($seats[$nr] == $defSeats){
                                         echo "<option selected=\"selected\" value=\"$seats[$nr]\">". $seats[$nr] ."</option>";
                                     }
                                     else{
                                         echo "<option value=\"$seats[$nr]\">". $seats[$nr] ."</option>";
                                     }
                                     $nr++;
                                 }
                                 ?>
                              </select>
                           </div>
                        </div>
                        <div class="form-group form-row">
                           <label class="col-sm-3" data-error="wrong" data-success="right" for="additionalDescription">Opis</label>
                           <div class="col">
                              <textarea name="additionalDescription" class="form-control form-control-sm validate"
                                 id="opis-nowy"
                                 rows="3"><?php echo htmlspecialchars($detale['additionalDescription']); ?></textarea>
                           </div>
                        </div>
                        <div class="form-group form-row">
                           <div class="col clearfix align-items-center row-eq-height text-center">
                              <h5>Właściciel pojazdu</h5>
                           </div>
                        </div>
                        <div class="form-group form-row">
                           <label class="col-sm-3" data-error="wrong" data-success="right"
                              for="ownerFirstName">Imię</label>
                           <div class="col-sm-9">
                              <input name="ownerFirstName" class="form-control form-control-sm validate"
                                 id="wlasciciel-imie-nowy"
                                 type="text" title="Podaj poprawne imie" required
                                 pattern="[A-Z]{1}[a-z]+" value="<?= $detale['owner']['firstName']; ?>">
                           </div>
                        </div>
                        <div class="form-group form-row">
                           <label class="col-sm-3" data-error="wrong" data-success="right"
                              for="ownerLastName">Nazwisko</label>
                           <div class="col-sm-9">
                              <input name="ownerLastName" class="form-control form-control-sm validate"
                                 id="wlasciciel-nazwisko-nowy"
                                 type="text" title="Podaj poprawne nazwisko"
                                 value="<?= $detale['owner']['lastName']; ?>" required pattern="[A-Z]{1}[a-z]+">
                           </div>
                        </div>
                        <div class="form-group form-row">
                           <label class="col-sm-3" data-error="wrong" data-success="right"
                              for="ownerEmail">Email</label>
                           <div class="col-sm-9">
                              <input name="ownerEmail" class="form-control form-control-sm validate"
                                 id="wlasciciel-email-nowy"
                                 type="text" title="Podaj poprawny adres email" required
                                 pattern="[A-Za-z0-9.]+[@][A-Za-z0-9]+[.][A-Za-z0-9]+"
                                 value="<?= $detale['owner']['email']; ?>">
                           </div>
                        </div>
                        <div class="form-group form-row">
                           <div class="col clearfix align-items-center row-eq-height text-center">
                              <button type="button" class="btn btn-link yellow-link" data-toggle="collapse"
                                 data-target="#wyposazenie-edit-collapse"><i class="fa fa-tachometer"
                                 aria-hidden="true"></i> Dodatkowe
                              wyposażenie
                              </button>
                              <div id="wyposazenie-edit-collapse" class="collapse row text-center">
                                 <div class="col-sm-12 align-items-center">
                                    <?php foreach ($data['listAllEquipment'] as $equipment) { ?>
                                    <div class="checkbox">
                                       <label><input type="checkbox" name="additionalEquipment[]"
                                          value="<?= $equipment['name'] ?>"> <?= $equipment['name'] ?>
                                       </label>
                                    </div>
                                    <?php } ?>
                                 </div>
                              </div>
                           </div>
                        </div>
                        <hr>
                        <div class="form-group form-row justify-content-center align-items-center">
                           <button type="submit" class="btn btn-green-submit align-items-center">Edytuj<i
                              class="fa fa-paper-plane-o ml-1"></i></button>
                        </div>
                     </form>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- !Modal edytuj pojazd -->
      <!-- Modal sprzedaj pojazd -->
      <div id="modalSprzedajPojazd" class="modal" role="dialog">
         <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
               <div class="modal-header text-center" style="background-color: #2EC4B6">
                  <h4 class="modal-title w-100 font-weight-bold">Sprzedać pojazd?</h4>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                  </button>
               </div>
               <div class="modal-body">
                  <div class="container-fluid">
                     <form method="POST" action="/pojazdy/sprzedaj/<?= $detale['id'] ?>">
                        <div class="form-group form-row">
                           <label class="col-sm-3" data-error="wrong" data-success="right"
                              for="kupujacyImie">Imię kupującego</label>
                           <div class="col-sm-9">
                              <input name="buyerFirstName" class="form-control form-control-sm validate"
                                 id="kupujacyImie"
                                 type="text" title="Podaj poprawne imie" required
                                 pattern="[A-Z]{1}[a-z]+" value="<?= $detale['owner']['firstName']; ?>">
                           </div>
                        </div>
                        <div class="form-group form-row">
                           <label class="col-sm-3" data-error="wrong" data-success="right"
                              for="kupujacyNazwisko">Nazwisko kupującego</label>
                           <div class="col-sm-9">
                              <input name="buyerLastName" class="form-control form-control-sm validate"
                                 id="kupujacyNazwisko"
                                 type="text" title="Podaj poprawne nazwisko"
                                 value="<?= $detale['owner']['lastName']; ?>" required pattern="[A-Z]{1}[a-z]+">
                           </div>
                        </div>
                        <div class="form-group form-row">
                           <label class="col-sm-3" data-error="wrong" data-success="right"
                              for="kupujacyEmail">Email kupującego</label>
                           <div class="col-sm-9">
                              <input id="kupujacyEmail" name="buyerEmail" class="form-control form-control-sm validate"
                                 type="text" title="Podaj poprawny adres email" required
                                 pattern="[A-Za-z0-9.]+[@][A-Za-z0-9]+[.][A-Za-z0-9]+"
                                 value="<?= $detale['owner']['email']; ?>">
                           </div>
                           <input type="hidden" name="price" value="<?= $detale['price'] ?>">
                           <input type="hidden" name="carId" value="<?= $detale['id'] ?>" id="idPojazdu">
                        </div>
                        <div class="form-group form-row justify-content-center align-items-center">
                           <button data-dismiss="modal" class="btn btn-cancel align-items-center"
                              style="margin-right: 1em">Anuluj <i class="fa fa-ban" aria-hidden="true"></i>
                           </button>
                           <button type="submit" class="btn btn-green-submit align-items-center">Sprzedaj<i
                              class="fa fa-paper-plane-o ml-1"></i></button>
                        </div>
                     </form>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- !Modal sprzedaj pojazd -->
      <section class="py-5 text-center"
         style="background-color: #f8f9fa; margin-bottom: 5em; position: relative; color: #011627;">
         <div class="container">
            <h1 style="color: #011627">Przeglądaj pojazdy</h1>
            <p class="lead">Wpisz czego szukasz na pasku wyszukiwania. Dopasuj wyniki za pomocą filtrów.</p>
            <div class="big-icon" id="bigIcon"><i class="fa fa-car" aria-hidden="true"></i></div>
         </div>
      </section>
      <div class="container" id="alerts" style="width: 30%"></div>
      <div class="container" style="width: 70%; max-width: 900px; margin-bottom: 5em">
         <div class="row">
            <!-- outer row -->
            <div class="col-sm-1"></div>
            <div class="col-sm-10">
               <div class="card ">
                  <div class="card-body align-items-center row-eq-height">
                     <div class="row">
                        <!-- inner row -->
                        <aside class="col-sm-4  vertical-center">
                           <img src="/views/pojazdy/img/top-gear.jpg"
                              class="img-responsive img-box img-thumbnail fakeimg">
                        </aside>
                        <aside class="col-sm-8">
                           <article>
                              <h3 class="title mb-3"><?= $detale['brand'] ?> <?= $detale['model'] ?></h3>
                              <p class="price-detail-wrap">
                                 <span class="price h3 text-warning"> 
                                 <span class="num"><?= $detale['price'] ?></span><span class="currency">zł</span>
                                 </span>
                              </p>
                              <!-- price-detail-wrap .// -->
                              <dl class="item-property">
                                 <dt>Opis</dt>
                                 <dd>
                                    <p><?= $detale['additionalDescription'] ?></p>
                                 </dd>
                              </dl>
                           </article>
                        </aside>
                     </div>
                     <!-- inner row -->
                     <div class="row">
                        <!-- inner row -->
                        <div class="col-sm-4">
                           <dl class="param param-feature">
                              <dt>Numer rejestracyjny</dt>
                              <dd><?= $detale['registrationNumber'] ?></dd>
                           </dl>
                           <!-- item-property-hor .// -->
                           <dl class="param param-feature">
                              <dt>Przebieg</dt>
                              <dd><?= $detale['mileage'] ?></dd>
                           </dl>
                           <!-- item-property-hor .// -->
                           <dl class="param param-feature">
                              <dt>Kolor</dt>
                              <dd><?= $detale['color'] ?></dd>
                           </dl>
                           <!-- item-property-hor .// -->
                        </div>
                        <div class="col-sm-4">
                           <dl class="param param-feature">
                              <dt>Rok produkcji</dt>
                              <dd><?= $detale['productionYear'] ?></dd>
                           </dl>
                           <!-- item-property-hor .// -->
                           <dl class="param param-feature">
                              <dt>Liczba miejsc</dt>
                              <dd><?= $detale['seatsNumber'] ?></dd>
                           </dl>
                           <!-- item-property-hor .// -->
                           <dl class="param param-feature">
                              <dt>Wyposażenie dodatkowe</dt>
                              <dd>
                                 <?php foreach ($detale['additionalEquipment'] as $key => $value) {
                                    end($detale['additionalEquipment']);
                                    $keyLast = key($detale['additionalEquipment']);
                                    if($key != $keyLast) {
                                        echo $detale['additionalEquipment'][$key] . ', ';
                                    } else {
                                        echo $detale['additionalEquipment'][$key];
                                    }
                                    }
                                    ?>
                              </dd>
                           </dl>
                           <!-- item-property-hor .// -->
                        </div>
                        <div class="col-sm-4">
                           <dl class="param param-feature">
                              <dt>VIN</dt>
                              <dd><?= $detale['vin']; ?></dd>
                           </dl>
                           <!-- item-property-hor .// -->
                           <dl class="param param-feature">
                              <dt>Liczba drzwi</dt>
                              <dd><?= $detale['doorsNumber']; ?></dd>
                           </dl>
                           <dl class="param param-feature">
                              <dt>Sprzedany</dt>
                              <dd><?php
                                 if($detale['sold'] == true) echo 'TAK';
                                 else echo 'NIE';
                                 ?></dd>
                           </dl>
                           <!-- item-property-hor .// -->
                        </div>
                     </div>
                     <!-- inner row -->
                     <hr>
                     <div class="form-group form-row">
                        <div class="col clearfix align-items-center row-eq-height text-center">
                           <h5>Właściciel pojazdu</h5>
                        </div>
                     </div>
                     <div class="row">
                        <!-- inner row -->
                        <div class="col-sm-4">
                           <dl class="param param-feature">
                              <dt>Imię</dt>
                              <dd><?= $detale['owner']['firstName']; ?></dd>
                           </dl>
                           <!-- item-property-hor .// -->
                        </div>
                        <div class="col-sm-4">
                           <dl class="param param-feature">
                              <dt>Nazwisko</dt>
                              <dd><?= $detale['owner']['lastName']; ?></dd>
                           </dl>
                           <!-- item-property-hor .// -->
                        </div>
                        <div class="col-sm-4">
                           <dl class="param param-feature">
                              <dt>Adres email</dt>
                              <dd id="mailWlasciciela"><?= $detale['owner']['email']; ?></dd>
                           </dl>
                           <!-- item-property-hor .// -->
                        </div>
                     </div>
                     <!-- inner row -->
                     <hr>
                     <div class="row row-eq-height">
                        <div class="col-sm-12">
                           <a href="../../pojazdy/" class="btn btn-lg btn-link green-link"><i
                              class="fa fa-chevron-left" aria-hidden="true"></i><i class="fa fa-chevron-left"
                              aria-hidden="true"></i></a>
                           <button class="btn btn-lg btn-yellow-sell pull-right" style="margin-left: 0.5em"
                              data-toggle="modal" data-target="#modalSprzedajPojazd"<?php
                                 if($detale['sold'] == true) echo ' disabled';
                                 ?>>Sprzedaj</button>
                           <a href="#" class="btn btn-lg btn-outline-dark text-uppercase pull-right"
                              data-toggle="modal" data-target="#modalEdytujPojazd"><i class="fa fa-cog"
                              aria-hidden="true"></i></a>
                           <button id="acceptaceConfirmButton" style="margin-right: 10px;" class="btn btn-lg btn-outline-dark text-uppercase pull-right"><i class="fa fa-envelope-o" aria-hidden="true"></i></button>
                           <?php
                              if($detale['sold'] == true) echo '<a href="http://10.7.32.21:8080/komis-sam/sellCar/generateSoldConfirmation/'.$detale['id'].'" target="_blank" class="btn btn-lg btn-outline-dark text-uppercase pull-right" style="margin-right: 10px;"><i class="fa fa-file-text" aria-hidden="true"></i></a>';
                              ?>
                        </div>
                     </div>
                  </div>
               </div>
               <!-- card -->
            </div>
            <!-- col sm 12 -->
         </div>
         <!-- outer row -->
      </div>
      <!--Footer-->
      <footer class="page-footer font-small pt-4 mt-4 car-item-body white-text">
         <!--Footer Links-->
         <div class="container text-center text-md-left">
            <!-- Footer links -->
            <div class="row text-center text-md-left mt-3 pb-3">
               <!--First column-->
               <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
                  <h6 class="text-uppercase mb-4 font-weight-bold">Analitycy</h6>
                  <ul class="list-unstyled">
                     <li>
                        <a href="#!" class="white-link">***</a>
                     </li>
                     <li>
                        <a href="#!" class="white-link">***</a>
                     </li>
                     <li>
                        <a href="#!" class="white-link">***</a>
                     </li>
                  </ul>
               </div>
               <!--/.First column-->
               <hr class="w-100 clearfix d-md-none">
               <!--Second column-->
               <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
                  <h6 class="text-uppercase mb-4 font-weight-bold">Backend</h6>
                  <ul class="list-unstyled">
                     <li>
                        <a href="#!" class="white-link">***</a>
                     </li>
                     <li>
                        <a href="#!" class="white-link">***</a>
                     </li>
                     <li>
                        <a href="#!" class="white-link">***</a>
                     </li>
                  </ul>
               </div>
               <!--/.Second column-->
               <hr class="w-100 clearfix d-md-none">
               <!--Third column-->
               <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
                  <h6 class="text-uppercase mb-4 font-weight-bold">Frontend</h6>
                  <ul class="list-unstyled">
                     <li>
                        <a href="#!" class="white-link">Mateusz Malec</a>
                     </li>
                     <li>
                        <a href="#!" class="white-link">***</a>
                     </li>
                  </ul>
               </div>
               <!--/.Third column-->
               <hr class="w-100 clearfix d-md-none">
               <!--Fourth column-->
               <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
                  <h6 class="text-uppercase mb-4 font-weight-bold">Kierownik Projektu</h6>
                  <ul class="list-unstyled">
                     <li>
                        <a href="#!" class="white-link">***</a>
                     </li>
                  </ul>
               </div>
               <!--/.Fourth column-->
               <!--Fifth column-->
               <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
                  <h6 class="text-uppercase mb-4 font-weight-bold">Testerzy</h6>
                  <ul class="list-unstyled">
                     <li>
                        <a href="#!" class="white-link">***</a>
                     </li>
                     <li>
                        <a href="#!" class="white-link">***</a>
                     </li>
                     <li>
                        <a href="#!" class="white-link">***</a>
                     </li>
                  </ul>
               </div>
               <!--/.Fifth column-->
               <!--Sixth column-->
               <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
                  <h6 class="text-uppercase mb-4 font-weight-bold">Kontrola Jakości</h6>
                  <ul class="list-unstyled">
                     <li>
                        <a href="#!" class="white-link">***</a>
                     </li>
                  </ul>
               </div>
               <!--/.Sixth column-->
            </div>
            <!-- Footer links -->
         </div>
         <!-- Copyright-->
         <div class="footer-copyright py-3 text-center" style="background-color: #222">
            © 2018
            <a href="#!" class="yellow-link">
            <strong>I5B1N1</strong>
            </a>
         </div>
         <!--/.Copyright -->
      </footer>
      <!--/.Footer-->
      <script src="/views/pojazdy/js/new-brand-model-dropdown.js"></script>
      <script src="/views/pojazdy/js/edit-brand-model-dropdown.js"></script>
   </body>
</html>